version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1
  
    working_directory: /go/src/github.com/MrHuxu/leetcode150

    environment:
      GO111MODULE: "on"

    steps:
      - checkout
      - run: cd problems && go mod download

      - run:
          name: Run unit tests
          command: make test