name: Test Solutions

on: [push]
 
jobs:

  test-go-solutions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Run Tests
      run: cd go && go mod download && go test ./...

  test-rust-solutions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: cd rust && cargo test --verbose