name: Test Solutions

on: [push]
 
jobs:

  test-go-solutions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Unit Tests
      run: cd go && go mod download && go test ./...
