name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: cd website && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Move document and solution files
        run: mv documents website/ && mkdir website/solutions && mv go website/solutions/ && mv rust website/solutions/ && mv java website/solutions/
      - name: Build Tailwind
        run: cd website && npx tailwindcss -o ./assets/built.css --minify
      - name: Build Project Artifacts
        run: cd website && vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: cd website && vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
